"""Generate .importlinter config from graph evidence."""

from __future__ import annotations

import os
import textwrap
from datetime import datetime, timezone
from pathlib import Path

import networkx as nx

from codescaffold.graphify.snapshot import GraphSnapshot

from .cycles import detect_package_cycles
from .models import ContractArtifact
from .package_graph import build_package_dag, detect_root_package

_CONFIG_FILENAME = ".importlinter"


def generate_importlinter_config(repo_path: Path, snap: GraphSnapshot) -> ContractArtifact:
    """Generate .importlinter from current graph structure.

    If cycles are detected in the package graph, returns an artifact with
    cycles_detected populated and written=False (no file is written).

    If the graph is acyclic, writes .importlinter and returns written=True.
    """
    repo_path = Path(repo_path).resolve()
    cycles = detect_package_cycles(repo_path, snap)

    config_path = str(repo_path / _CONFIG_FILENAME)

    if cycles:
        return ContractArtifact(
            config_path=config_path,
            layers=(),
            forbidden=(),
            cycles_detected=tuple(cycles),
            written=False,
        )

    root_package = detect_root_package(repo_path)
    dag = build_package_dag(snap, root_package=root_package)

    # Condense SCCs so topological_generations works even if the graphify
    # semantic graph has cycles (which are not Python import cycles).
    sccs = list(nx.strongly_connected_components(dag))
    scc_dag = nx.condensation(dag, scc=sccs)
    layers: tuple[tuple[str, ...], ...] = tuple(
        tuple(pkg for scc_id in gen for pkg in sorted(sccs[scc_id]))
        for gen in nx.topological_generations(scc_dag)
    )

    # Strip root_package prefix for relative names in the contract
    def _short(pkg: str) -> str:
        prefix = root_package + "."
        return pkg[len(prefix):] if pkg.startswith(prefix) else pkg

    short_layers: tuple[tuple[str, ...], ...] = tuple(
        tuple(_short(p) for p in layer) for layer in layers
    )

    # Derive forbidden from graphify surprising connections
    from codescaffold.graphify.analysis import surprises
    surprise_edges = surprises(snap, top_n=5)
    forbidden_pairs: list[tuple[str, str]] = []
    node_to_pkg: dict[str, str] = {}
    G = snap.graph
    for node in G.nodes():
        src = G.nodes[node].get("source_file", "")
        from .package_graph import _file_to_subpackage
        pkg = _file_to_subpackage(src)
        if pkg:
            node_to_pkg[node] = pkg

    for edge in surprise_edges:
        sp = node_to_pkg.get(edge.source)
        tp = node_to_pkg.get(edge.target)
        if sp and tp and sp != tp:
            pair = (_short(sp), _short(tp))
            if pair not in forbidden_pairs:
                forbidden_pairs.append(pair)

    config_text = _render_config(root_package, short_layers, forbidden_pairs, snap.graph_hash)
    Path(config_path).write_text(config_text)

    return ContractArtifact(
        config_path=config_path,
        layers=short_layers,
        forbidden=tuple(forbidden_pairs),
        cycles_detected=(),
        written=True,
    )


def _render_config(
    root_package: str,
    layers: tuple[tuple[str, ...], ...],
    forbidden: list[tuple[str, str]],
    graph_hash: str,
) -> str:
    timestamp = datetime.now(tz=timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    lines: list[str] = [
        f"# AUTO-GENERATED by codescaffold {timestamp} from graph_hash {graph_hash[:12]}",
        "# Do not edit by hand — regenerate via the `contracts` MCP tool.",
        "",
        "[importlinter]",
        "root_packages =",
        f"    {root_package}",
        "",
        "[importlinter:contract:layers]",
        "name = Layer contract",
        "type = layers",
    ]

    # Emit layers from top (most downstream) to bottom (most upstream)
    layer_strs = [" | ".join(sorted(layer)) for layer in layers if layer]
    if layer_strs:
        lines.append("layers =")
        for ls in layer_strs:
            lines.append(f"    {ls}")
    lines.append("containers =")
    lines.append(f"    {root_package}")

    if forbidden:
        lines += ["", "[importlinter:contract:no-surprising-deps]"]
        lines += ["name = No surprising dependencies", "type = forbidden"]
        lines.append("source_modules =")
        for src, _ in forbidden:
            lines.append(f"    {root_package}.{src}")
        lines.append("forbidden_modules =")
        for _, tgt in forbidden:
            lines.append(f"    {root_package}.{tgt}")

    lines.append("")
    return os.linesep.join(lines)
