from __future__ import annotations

import datetime
import logging
import re
from itertools import combinations
from pathlib import Path
from typing import Literal

import grimp
import networkx as nx
from pydantic import BaseModel

from refactor_plan.interface.cluster_view import ClusterView
from refactor_plan.layout import ProjectLayout
from refactor_plan.planning.proposal import RefactorPlan

logger = logging.getLogger(__name__)

_PROVENANCE_MARKER = "# AUTO-GENERATED by codescaffold"


class ContractSpec(BaseModel):
    name: str
    contract_type: Literal["independence", "layers", "forbidden"]
    modules: list[str] = []
    source_modules: list[str] = []
    forbidden_modules: list[str] = []
    layers: list[list[str]] = []


class CycleBreakSuggestion(BaseModel):
    cycle: list[str]
    edge: str               # "pkg_a → pkg_b" — the edge to break
    cause: str              # which file/import causes the edge
    suggestion: str         # how to break it


class ContractArtifact(BaseModel):
    config_path: str
    contracts: list[ContractSpec] = []
    was_hand_edited: bool = False
    graph_mtime_iso: str = ""
    skipped_reason: str = ""
    cycles_detected: list[list[str]] = []
    cycle_break_suggestions: list[CycleBreakSuggestion] = []


# ---------------------------------------------------------------------------
# grimp helpers
# ---------------------------------------------------------------------------

def _build_package_map(root_package: str) -> dict[str, set[str]]:
    """Return subpackage → set of imported subpackages using grimp squashing."""
    try:
        g = grimp.build_graph(root_package)
    except Exception as exc:
        logger.warning("grimp failed to build graph for %s: %s", root_package, exc)
        return {}

    subpkgs = sorted({
        m.split(".")[1]
        for m in g.modules
        if m.count(".") >= 1 and m.startswith(root_package + ".")
    })

    for sub in subpkgs:
        try:
            g.squash_module(f"{root_package}.{sub}")
        except Exception:
            pass

    pkg_map: dict[str, set[str]] = {}
    for sub in subpkgs:
        full = f"{root_package}.{sub}"
        try:
            direct = g.find_modules_directly_imported_by(full)
        except Exception:
            direct = set()
        pkg_map[sub] = {
            d.split(".")[1]
            for d in direct
            if d.startswith(root_package + ".") and d.count(".") >= 1
        }

    return pkg_map


def _library_packages(pkg_map: dict[str, set[str]]) -> list[str]:
    """
    Packages imported by at least one other package — i.e., library modules, not
    entry points.  Entry points (mcp_server, demo, etc.) are top-of-chain consumers
    that import everything but nothing imports them.
    """
    imported_by_anyone = {tgt for tgts in pkg_map.values() for tgt in tgts}
    return sorted(pkg for pkg in pkg_map if pkg in imported_by_anyone)


def _find_cycles(pkg_map: dict[str, set[str]]) -> list[list[str]]:
    dag = nx.DiGraph()
    for src, tgts in pkg_map.items():
        for tgt in tgts:
            dag.add_edge(src, tgt)
    return list(nx.simple_cycles(dag))


def _topo_layers(pkg_map: dict[str, set[str]]) -> list[list[str]] | None:
    dag = nx.DiGraph()
    for src, tgts in pkg_map.items():
        for tgt in tgts:
            dag.add_edge(src, tgt)
    try:
        return [sorted(layer) for layer in nx.topological_generations(dag)]
    except nx.NetworkXUnfeasible:
        return None


# ---------------------------------------------------------------------------
# Cycle analysis — fuses grimp data with graphify community context
# ---------------------------------------------------------------------------

def _analyze_cycles(
    cycles: list[list[str]],
    pkg_map: dict[str, set[str]],
    view: ClusterView,
    source_root: Path,
    repo_root: Path,
    root_package: str,
) -> list[CycleBreakSuggestion]:
    """
    For each cycle edge, find the concrete import and cross-reference graphify
    community data to suggest which symbol to move or extract.
    """
    # Build a fresh (non-squashed) graph for import-level detail queries
    try:
        detail_graph = grimp.build_graph(root_package)
    except Exception:
        return []

    suggestions: list[CycleBreakSuggestion] = []
    seen_edges: set[tuple[str, str]] = set()

    for cycle in cycles:
        for i, src_sub in enumerate(cycle):
            tgt_sub = cycle[(i + 1) % len(cycle)]
            edge_key = (src_sub, tgt_sub)
            if edge_key in seen_edges:
                continue
            seen_edges.add(edge_key)

            src_full = f"{root_package}.{src_sub}"
            tgt_full = f"{root_package}.{tgt_sub}"

            # Find which specific module-level imports create this edge
            cause_lines: list[str] = []
            try:
                matches = detail_graph.find_matching_direct_imports(
                    f"{src_full}.* -> {tgt_full}.*"
                )
                for m in matches[:3]:
                    importer = m.get("importer", "").split(".")[-1]
                    imported = m.get("imported", "").split(".")[-1]
                    cause_lines.append(f"{importer}.py imports {imported}")
            except Exception:
                pass

            cause = "; ".join(cause_lines) or f"{src_sub} imports {tgt_sub}"
            suggestion_text = _suggest_cycle_break(
                src_sub, tgt_sub, cause, view, source_root, repo_root, root_package
            )

            suggestions.append(CycleBreakSuggestion(
                cycle=cycle,
                edge=f"{src_sub} → {tgt_sub}",
                cause=cause,
                suggestion=suggestion_text,
            ))
            if len(suggestions) >= 10:
                return suggestions

    return suggestions


def _suggest_cycle_break(
    src_sub: str,
    tgt_sub: str,
    cause: str,
    view: ClusterView,
    source_root: Path,
    repo_root: Path,
    root_package: str,
) -> str:
    """
    Use the graphify graph to determine whether the coupling is expected (same community)
    or surprising (different communities) and emit a concrete suggestion.
    """
    # Find all nodes in src_sub and tgt_sub packages from the graphify graph
    src_prefix = str(source_root / src_sub)
    tgt_prefix = str(source_root / tgt_sub)

    src_nodes = {
        nid for nid, attrs in view.G.nodes(data=True)
        if _node_in_package(attrs.get("source_file", ""), src_prefix, repo_root)
    }
    tgt_nodes = {
        nid for nid, attrs in view.G.nodes(data=True)
        if _node_in_package(attrs.get("source_file", ""), tgt_prefix, repo_root)
    }

    # Check if the importing node (src) and imported node (tgt) share a graphify community
    shared_community_pairs: list[str] = []
    for src_nid in src_nodes:
        src_comm = view.G.nodes[src_nid].get("community")
        for tgt_nid in tgt_nodes:
            tgt_comm = view.G.nodes[tgt_nid].get("community")
            if src_comm is not None and src_comm == tgt_comm:
                src_lbl = view.G.nodes[src_nid].get("label", src_nid)
                tgt_lbl = view.G.nodes[tgt_nid].get("label", tgt_nid)
                shared_community_pairs.append(f"{src_lbl} / {tgt_lbl}")

    if shared_community_pairs:
        pair_str = ", ".join(shared_community_pairs[:2])
        return (
            f"graphify places {pair_str} in the same community — "
            f"consider co-locating the imported symbol with its caller, "
            f"or extracting it to a shared module that neither {src_sub} nor {tgt_sub} "
            "owns (e.g. a models.py or types.py)."
        )

    return (
        f"graphify sees {src_sub} and {tgt_sub} as separate clusters. "
        f"Extract the shared symbol into a lower-level module (e.g. {root_package}.models or "
        f"{root_package}.types) that neither {src_sub} nor {tgt_sub} depends on."
    )


def _node_in_package(source_file: str, pkg_prefix: str, repo_root: Path) -> bool:
    if not source_file:
        return False
    p = Path(source_file)
    if not p.is_absolute():
        p = (repo_root / p).resolve()
    return str(p).startswith(pkg_prefix)


# ---------------------------------------------------------------------------
# Contract derivation
# ---------------------------------------------------------------------------

def _derive_layers_contract(
    pkg_map: dict[str, set[str]],
    root_package: str,
) -> ContractSpec | None:
    layers = _topo_layers(pkg_map)
    if layers is None or len(layers) < 2:
        return None
    qualified = [[f"{root_package}.{sub}" for sub in layer] for layer in layers]
    return ContractSpec(name="package_layers", contract_type="layers", layers=qualified)


def _derive_independence_contracts(
    pkg_map: dict[str, set[str]],
    root_package: str,
) -> list[ContractSpec]:
    """
    Find the largest set of library packages where no two members directly import
    each other (maximum independent set in the pairwise-conflict graph).

    Entry-point packages (not imported by anything) are excluded because they are
    consumers of the library, not part of the architecture being enforced.
    """
    lib_pkgs = _library_packages(pkg_map)
    if len(lib_pkgs) < 2:
        return []

    # Conflict pairs: (A, B) if A directly imports B or B directly imports A
    conflicts: set[frozenset] = {
        frozenset([src, tgt])
        for src, tgts in pkg_map.items()
        for tgt in tgts
        if src in set(lib_pkgs) and tgt in set(lib_pkgs)
    }

    # Maximum independent set — brute-force is fine for N ≤ ~15
    best: list[str] = []
    for size in range(len(lib_pkgs), 1, -1):
        for subset in combinations(lib_pkgs, size):
            if all(frozenset([a, b]) not in conflicts for a, b in combinations(subset, 2)):
                best = sorted(subset)
                break
        if best:
            break

    if len(best) < 2:
        return []

    return [ContractSpec(
        name="independent_packages",
        contract_type="independence",
        modules=[f"{root_package}.{sub}" for sub in best],
    )]


def _derive_forbidden_contracts(
    view: ClusterView,
    source_root: Path,
    repo_root: Path,
    root_package: str,
) -> list[ContractSpec]:
    """Forbidden-import contracts from surprising cross-cluster connections."""
    label_to_file: dict[str, str] = {
        attrs.get("label", ""): attrs.get("source_file", "")
        for _, attrs in view.G.nodes(data=True)
        if attrs.get("label") and attrs.get("source_file")
    }

    contracts: list[ContractSpec] = []
    seen: set[tuple[str, str]] = set()

    for s in view.surprising_connections[:10]:
        source_files = s.get("source_files", [])
        if len(source_files) >= 2:
            src_file, tgt_file = str(source_files[0]), str(source_files[1])
        else:
            src_file = label_to_file.get(s.get("source", ""), "")
            tgt_file = label_to_file.get(s.get("target", ""), "")

        if not src_file or not tgt_file:
            continue

        src_pkg = _file_to_subpackage(Path(src_file), source_root, repo_root, root_package)
        tgt_pkg = _file_to_subpackage(Path(tgt_file), source_root, repo_root, root_package)

        if not src_pkg or not tgt_pkg or src_pkg == tgt_pkg:
            continue
        if _is_placeholder(src_pkg) or _is_placeholder(tgt_pkg):
            continue

        pair = (src_pkg, tgt_pkg)
        if pair in seen:
            continue
        seen.add(pair)

        short_src = src_pkg.split(".")[-1]
        short_tgt = tgt_pkg.split(".")[-1]
        name = f"no_{short_src}_to_{short_tgt}"
        contracts.append(ContractSpec(
            name=name,
            contract_type="forbidden",
            source_modules=[src_pkg],
            forbidden_modules=[tgt_pkg],
        ))

    return contracts


def _file_to_subpackage(
    file_path: Path, source_root: Path, repo_root: Path, root_package: str
) -> str | None:
    p = file_path if file_path.is_absolute() else (repo_root / file_path)
    try:
        rel = p.resolve().relative_to(source_root.resolve())
    except ValueError:
        return None
    parts = rel.parts
    if not parts:
        return None
    pkg_parts = [parts[0]]
    if len(parts) >= 2 and not parts[1].endswith(".py"):
        pkg_parts.append(parts[1])
    return ".".join(pkg_parts) if len(pkg_parts) >= 2 else None


def _is_placeholder(module_name: str) -> bool:
    return bool(re.search(r"\bpkg_\d{3}\b", module_name))


# ---------------------------------------------------------------------------
# Rendering
# ---------------------------------------------------------------------------

def _render_contract(spec: ContractSpec) -> str:
    lines = [
        f"\n[importlinter:contract:{spec.name}]",
        f"name = {spec.name.replace('_', ' ')}",
        f"type = {spec.contract_type}",
    ]
    if spec.contract_type == "independence":
        lines.append("modules =")
        for m in spec.modules:
            lines.append(f"    {m}")
    elif spec.contract_type == "forbidden":
        lines.append("source_modules =")
        for m in spec.source_modules:
            lines.append(f"    {m}")
        lines.append("forbidden_modules =")
        for m in spec.forbidden_modules:
            lines.append(f"    {m}")
    elif spec.contract_type == "layers":
        lines.append("layers =")
        for i, layer in enumerate(spec.layers):
            for m in layer:
                lines.append(f"    {m}")
            if i < len(spec.layers) - 1:
                lines.append("    ---")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Lifecycle helpers
# ---------------------------------------------------------------------------

def _graph_mtime_iso(graph_json: Path) -> str:
    try:
        mtime = graph_json.stat().st_mtime
        return datetime.datetime.fromtimestamp(mtime).isoformat(timespec="seconds")
    except OSError:
        return "unknown"


def _is_hand_edited(config_path: Path) -> bool:
    if not config_path.exists():
        return False
    try:
        first_line = config_path.read_text(encoding="utf-8").splitlines()[:1]
    except OSError:
        return False
    return not (first_line and first_line[0].startswith(_PROVENANCE_MARKER))


def check_staleness(config_path: Path, graph_json: Path) -> tuple[bool, str]:
    """Return (is_stale, reason). Stale when graph is newer than stored mtime."""
    if not config_path.exists():
        return True, "No contracts file found — run contracts first."
    if _is_hand_edited(config_path):
        return False, "Contracts were hand-edited — staleness not tracked."
    current_mtime = _graph_mtime_iso(graph_json)
    for line in config_path.read_text(encoding="utf-8").splitlines():
        if "mtime:" in line:
            stored = line.split("mtime:", 1)[1].strip().rstrip(")")
            if stored != current_mtime:
                return True, f"Graph changed (stored {stored}, current {current_mtime})."
            return False, "Contracts are up to date."
    return True, "No mtime record — run contracts to refresh."


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def generate_contracts(
    refactor_plan: RefactorPlan,
    view: ClusterView,
    graph_json: Path,
    repo_root: Path,
    layout: ProjectLayout,
    force: bool = False,
) -> ContractArtifact:
    """Emit .importlinter contracts from current cluster structure."""
    config_path = repo_root / ".importlinter"
    mtime = _graph_mtime_iso(graph_json)

    if _is_hand_edited(config_path) and not force:
        return ContractArtifact(
            config_path=str(config_path),
            was_hand_edited=True,
            graph_mtime_iso=mtime,
            skipped_reason=(
                f"{config_path.name} exists and was not generated by codescaffold. "
                "Pass force=True to overwrite."
            ),
        )

    root_package = layout.root_package
    source_root = layout.source_root

    pkg_map = _build_package_map(root_package)
    cycles = _find_cycles(pkg_map)

    if cycles:
        logger.warning(
            "%d import cycle(s) detected — layers contract skipped. "
            "Run contracts to see cycle-break suggestions.",
            len(cycles),
        )

    layers = _derive_layers_contract(pkg_map, root_package) if not cycles else None
    independence = _derive_independence_contracts(pkg_map, root_package)
    forbidden = _derive_forbidden_contracts(view, source_root, repo_root, root_package)
    all_contracts = ([layers] if layers else []) + independence + forbidden

    cycle_suggestions = _analyze_cycles(
        cycles, pkg_map, view, source_root, repo_root, root_package
    )

    cycle_header_lines = (
        ["# Cycles detected (layers contract skipped):"]
        + [f"#   {' → '.join(c + [c[0]])}" for c in cycles[:5]]
        if cycles
        else []
    )

    header = "\n".join([
        f"{_PROVENANCE_MARKER} on {mtime}",
        f"# Graph: {graph_json.name} (mtime: {mtime})",
        "# DO NOT EDIT — run contracts to refresh",
    ] + cycle_header_lines + [
        "",
        "[importlinter]",
        "root_packages =",
        f"    {root_package}",
    ])

    contract_body = "".join(_render_contract(spec) for spec in all_contracts)
    config_path.write_text(header + contract_body + "\n", encoding="utf-8")

    return ContractArtifact(
        config_path=str(config_path),
        contracts=all_contracts,
        graph_mtime_iso=mtime,
        cycles_detected=cycles,
        cycle_break_suggestions=cycle_suggestions,
    )
